server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  port: 80
  servlet:
    context-path: /images/

spring:
  servlet:
    multipart:
      max-file-size: 50MB

aws:
  access-key:
  secret-key:
  s3-bucket-name: